name: "PR Environments"
on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
jobs:
  env0_pr_environment:
    name: "PR Environment"
    runs-on: ubuntu-16.04
    container: node:12
    env:
      ACTION: deploy
    steps:
      - name: Set Action
        if: github.event.action == 'closed'
        run: echo "::set-env name=ACTION::destroy"
      - name: Install env0 CLI
        run: yarn global add @env0/cli
      - name: Run CLI
        run: >
          env0 $ACTION
          --apiKey ${{ secrets.ENV0_API_KEY_ID }}
          --apiSecret ${{ secrets.ENV0_API_KEY_SECRET }}
          --organizationId ${{ secrets.ENV0_ORG_ID }}
          --projectId ${{ secrets.ENV0_PROJECT_ID }}
          --blueprintId ${{ secrets.ENV0_BLUEPRINT_ID }}
          --environmentName "${{ github.head_ref }}"
          --revision "${{ github.head_ref }}"
